version: '3.8'
services:
  lm_theory:
    build: 
      context: ./knowledgebases/lm_theory
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
  iipa_backend:
    build: 
      context: ./iipa_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

